Update automerge.yml

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -24,16 +24,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Check PR details
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const pr_number = ${{ github.event.inputs.pr_number || github.event.pull_request.number }};
-            if (pr_number) {
-              console.log(`PR number: ${pr_number}`);
-            } else {
-              console.log('This workflow is not triggered by a pull request event.');
-            }
+      - name: Validate PR number
+        run: |
+          if [[ -z "${{ github.event.inputs.pr_number }}" ]]; then
+            echo "Error: Pull request number is required!";
+            exit 1;
+          else
+            echo "PR Number: ${{ github.event.inputs.pr_number }}";
+          fi
 
       - name: Check if PR merged
         if: github.event.pull_request.merged == true
