Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,13 +32,20 @@ jobs:
 
       - name: Trigger Build Workflow via API
         run: |
-          response=$(curl -X POST \
-             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-             -H "Accept: application/vnd.github.v3+json" \
+            response=$(curl -s -w "%{http_code}" -X POST \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
-             -d '{"ref":"refs/heads/${{ github.event.pull_request.head.ref }}"}')
-          echo "Build trigger response: $response"
-          echo "Response code: $(echo $response | jq -r '.message')"
+            -d '{"ref":"refs/heads/${{ github.event.pull_request.head.ref }}"}')
+            http_code=$(echo "$response" | tail -n 1)
+            body=$(echo "$response" | head -n -1)
+
+            echo "Response Status Code: $http_code"
+            echo "Response Body: $body"
+            if [[ "$http_code" != "201" ]]; then
+                echo "Failed to trigger build workflow. Status code: $http_code"
+            exit 1
+            fi
           
   # 2. Wait for Build Workflow to Complete
   wait_for_build:
